# Generated by Django 3.0.8 on 2020-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200905_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_binary',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/profile.svg', null=True, upload_to='images/profiles', verbose_name='Avatar'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
