# Generated by Django 3.0.8 on 2020-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200905_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.svg', null=True, upload_to='profiles/', verbose_name='Avatar'),
        ),
    ]
