# Generated by Django 3.0.8 on 2020-09-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200905_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.svg', null=True, upload_to='stocks/', verbose_name='Avatar'),
        ),
    ]
