# Generated by Django 3.0.8 on 2020-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200914_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/profiles/profile.png', null=True, upload_to='img/profiles', verbose_name='Avatar'),
        ),
    ]
