# Generated by Django 3.0.8 on 2020-09-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200914_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dividend_income',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Dividend income'),
        ),
    ]
