# Generated by Django 3.0.8 on 2020-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200917_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, default=5000, null=True, verbose_name='Balance'),
        ),
    ]
