# Generated by Django 3.0.8 on 2020-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('avatar', models.ImageField(blank=True, default='profile.svg', null=True, upload_to='profiles/', verbose_name='Avatar')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cost')),
                ('dividend_income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dividend income')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'Stock',
            },
        ),
    ]
