# Generated by Django 3.0.8 on 2020-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend_income',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Dividend income'),
        ),
    ]
