# Generated by Django 3.0.8 on 2020-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20200914_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.svg', null=True, upload_to='img/stocks', verbose_name='Avatar'),
        ),
    ]
