# Generated by Django 3.0.8 on 2020-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20200914_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avatar',
            field=models.ImageField(blank=True, default='img/stocks/stock.png', null=True, upload_to='img/stocks', verbose_name='Avatar'),
        ),
    ]
