# Generated by Django 3.0.8 on 2020-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_mystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Count'),
        ),
    ]
