# Generated by Django 3.0.8 on 2020-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
    ]
