# Generated by Django 3.0.8 on 2020-09-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20200917_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cost'),
        ),
    ]
