# Generated by Django 3.0.8 on 2020-09-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20200918_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='list_costs',
            field=models.TextField(null=True, verbose_name='List costs'),
        ),
    ]
