# Generated by Django 3.0.8 on 2020-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_stock_list_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='list_costs',
            field=models.TextField(default='[]', null=True, verbose_name='List costs'),
        ),
    ]
