# Generated by Django 3.0.8 on 2020-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20200918_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cost'),
        ),
    ]
