# Generated by Django 3.0.8 on 2020-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20200918_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGrowthRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_multiplier', models.FloatField(blank=True, default=1, null=True, verbose_name='Starting multiplier')),
                ('finite_factor', models.FloatField(blank=True, default=1, null=True, verbose_name='Finite factor')),
            ],
            options={
                'verbose_name': 'StockGrowthRates',
                'verbose_name_plural': 'StockGrowthRates',
                'db_table': 'StockGrowthRates',
            },
        ),
    ]
